version: 2
updates:
  # Poetry projects are handled by the `pip` ecosystem
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "02:00"
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "02:00"
    open-pull-requests-limit: 10
