# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.32.1
    hooks:
      - id: check-github-workflows
      - id: check-dependabot
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [--preview]
  - repo: https://github.com/adamchainz/blacken-docs
    rev: "1.19.1"
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==24.4.2
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
##{% if cookiecutter.linter == "ruff" %}
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff-check
        args: [ --fix ]
##{% elif cookiecutter.linter == "flake8" %}
  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies: [
          # Insert flake8 additional dependencies here
        ]
#{% endif %}
