name: docker

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:
  # Update docker hub retention policy
  schedule:
    - cron: "21 7 8 * *"

env:
  DOCKER_USERNAME: "{{ cookiecutter.dockerhub_username }}"
  PROJECT_NAME: "{{ cookiecutter.project_name }}"
  REGISTRY: ""
  DOCKER_BUILDKIT: "1"

concurrency:
  group: {% raw %}${{ github.workflow }}-${{ github.ref }}{% endraw %}
  cancel-in-progress: true

permissions: read-all

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Image full name variable
        run: echo "IMAGE_FULL_NAME=$(echo ${DOCKER_USERNAME}/${PROJECT_NAME})" >> $GITHUB_ENV

      - name: Prepare docker
        run: |
          echo "Making sure we are in the right directory, does nothing by default"
          pwd && echo "$GITHUB_WORKSPACE" && cd "$GITHUB_WORKSPACE"
          echo "Creating `.env` configuration file"
          pip install dump-env
          dump-env \
            -t .env.template \
            -p 'SECRET_' > .env
          echo "Debug information"
          docker info && docker-compose --version && git --version
          echo "Pulling cache"
          docker pull "${IMAGE_FULL_NAME}:dev" || true
          docker tag "${IMAGE_FULL_NAME}:dev" "${PROJECT_NAME}:dev" || true

      - name: Run checks
        run: |
          echo "Checking config"
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml config --quiet
          echo "Running checks"
          docker-compose build web
          docker-compose run --user=root --rm web ./ci.sh
          echo "Pushing back the result for future runs"
          docker tag "${PROJECT_NAME}:dev" "${IMAGE_FULL_NAME}:dev"
          docker push "${IMAGE_FULL_NAME}:dev"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          {% raw %}# token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos{% endraw %}

  # Releasing image, when in `master` branch or tag
  release-image:
    runs-on: ubuntu-latest
    needs: [checks]
    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v3

      - name: Set Image full name variable
        run: echo "IMAGE_FULL_NAME=$(echo ${DOCKER_USERNAME}/${PROJECT_NAME})" >> $GITHUB_ENV

      - name: Prepare docker
        run: |
          echo "Creating `.env` configuration file"
          pip install dump-env
          dump-env \
            -t .env.template \
            -p 'SECRET_' > .env
          echo "Login into Docker registry"
          {% raw %}echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login "$REGISTRY" -u "$DOCKER_USERNAME" --password-stdin{% endraw %}
          echo "Debug information"
          docker info && docker-compose --version && git --version

      - name: Pull cache
        run: |
          docker pull "${IMAGE_FULL_NAME}:latest" || true
          docker tag "${IMAGE_FULL_NAME}:latest" "${PROJECT_NAME}:latest" || true

      - name: Build image
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml build web

      - name: Set version env (GITHUB_REF:10 for extract version from non-v-tags without the 'refs/tags/' prefix)
        run: echo "VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
      - name: Set short version env
        run: echo "SHORT_VERSION=$(echo ${VERSION%.*})" >> $GITHUB_ENV

      - name: Add version tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml build web
          docker tag "${IMAGE_FULL_NAME}:latest" "${IMAGE_FULL_NAME}:${VERSION}"
          docker tag "${IMAGE_FULL_NAME}:latest" "${IMAGE_FULL_NAME}:${SHORT_VERSION}"

      - name: Push production images
        run: |
          echo "Showing debug information"
          docker image ls
          docker push "${IMAGE_FULL_NAME}" --all-tags
